### ISSUE TITLE
Speed up build and tests

### ISSUE THREAD

**Issue by yanirs** [Automattic/abacus#544]
This is a collection of ideas for speeding up the build and tests. We can chip away at the list if and when we have time. Feel free to edit if you come across more ideas.

- [x] Use a next-gen image that comes with browsers (https://github.com/Automattic/abacus/issues/48#issuecomment-701864507)
- [x] Look into using CircleCI parallelism (#351)
- [x] Speed up ExperimentForm test (#293)

**Comment by is4ac** [comment]
This has become an even bigger issue with the addition of #630. The ExperimentForm test now takes much longer now (several minutes on my machine). Not the worst thing in the world, but this could bump up the priority on this issue.

**Comment by aaronyan** [comment]
Closing this issue for now since the original improvements are complete and we haven't merged #630 yet.
