### ISSUE TITLE
Investigate AG-Grid enterprise

### ISSUE THREAD

**Issue by jessie-ross** [Automattic/abacus#652]
**We use AG-Grid for our grids, it is worth exploring their enterprise features for some of our needs:**
- Master-Detail view for metrics/experiments
- maybe: Row grouping, tree views

**Tasks:**
- [ ] [Investigate pricing](https://www.ag-grid.com/license-pricing.php).
- [ ] See if this is feasible at A8C.
- [ ] Evaluate the enterprise features before purchasing.

Related to #604

**Comment by razvanpapadopol** [comment]
Meanwhile, there has been released also [MUI Data Grid Pro](https://mui.com/x/react-data-grid/#features) as part of https://mui.com/x/ which we may consider as an alternative.

**Comment by aaronyan** [comment]
I've reached out to Anna privately, since she has experience renewing our Looker contract. I'll share an update later!
