### ISSUE TITLE
Add new recommendations

### ISSUE THREAD

**Issue by aaronyan** [Automattic/abacus#660]
Let's implement the new recommendations based on these designs (pbmo2S-14p-p2). Here's a summary:

## Sub-scopes
- [x] Change 'Recommendation' to 'Analysis' (🟩 🟩 🟩 🟩 🟩)
- [x] Add more types of analysis (🟩 🟩 🟩 🟩 🟩) #672
- [x] Add deployment recommendations (🟩 🟩 🟩 🟩 🟩) #674
- [ ] ~Add simplified square diagrams to metric overview header (🟩 🟩 🟩 🟨 ⬛) [WIP]~
- [x] Add credible intervals for relative change (🟩 🟩 🟩 🟩 🟨) #675

### Before

<img width="961" alt="group-58-2" src="https://user-images.githubusercontent.com/4505888/156828385-2825079a-88b8-4de0-8bf9-a9a97f991548.png">

### After

<img width="961" alt="group-58_3-1" src="https://user-images.githubusercontent.com/4505888/156828390-e2294f6d-bf57-4e53-9a44-181f8f545b7c.png">

## Change 'Recommendation' to 'Analysis'

We are moving away from the metric overview header showing "Recommendation" and replacing it with "Analysis". This may involve changing variable names in Abacus. 

## Add more types of analysis

Abacus currently has three recommendation types: “deploy {variant}”, “deploy any variation”, and “inconclusive”. We want to add more types of analysis, so you can better understand your experiment results even when there is not a clear winner.

- _{Variant} wins_ – There is high certainty that the variant is statistically and practically significant.
- _{Variant} ahead_ – Variant is ahead and is statistically different, but there is not enough certainty to say the change is practically significant.
- _{Variant} barely ahead_ – Variant is barely ahead and is statistically different, but there is high certainty that the change isn’t practically significant.
- _Inconclusive_ – There is not enough certainty to draw a conclusion at this time.
- _No difference_ – There is high certainty that difference in performance is not practically significant. Learn more.

<img width="1480" alt="Screen Shot 2022-04-14 at 11 20 48 AM" src="https://user-images.githubusercontent.com/4505888/163454099-ee03b071-512b-4585-bf26-686e01624248.png">

## Add deployment recommendations

Within the **overview** (see image of Google sheet), we should provide deployment recommendations only if certain conditions are met. Here is that flowchart:

<img width="1125" alt="152608705-5dd9f20a-a422-4598-81c8-ae5bf98aa126" src="https://user-images.githubusercontent.com/4505888/156829388-85625ccc-05c0-45df-984a-aee4f62c5620.png">

And here is the deployment recommendations:

- _Deploy {variant} with confidence_ – When a variant wins.
- _Deploy {variant} cautiously_ – For statistically significant results, but a variant did not show enough of a practical difference to win.
- _Deploy either variation_ – When the performance is not great enough to make a practical difference.
- _Not enough data to make a recommendation at this time_ – The current results has high uncertainty, and collecting more data may improve certainty.

## Add simplified square diagrams to metric overview header

In the metric overview header, we will introduce new simplified square diagrams. See the _After_ image above and the diagrams on the right-most side. The shaded regions correspond to the most recent metric value credible interval. The color will be dependent on the flow chart and indicate the following:

- Green (`#00d084`) – Enough data is available to make a deployment recommendation.
- Yellow (`#fcb900`) – More data is required before we can make a deployment recommendation.

## Add credible intervals for relative change

In the metric overview header, we will also add another credible interval visualization. See the _After_ image above and the diagrams on the left-side.

@dechov may help us with this feature and shared a [demo](https://observablehq.com/d/7895faa74230caf7) on how that might look.

**Comment by razvanpapadopol** [comment]
Change 'Recommendation' to 'Analysis' (🟩 🟩 🟩 🟨 ⬛)
- Update the UI and component props in https://github.com/Automattic/abacus/pull/667

**Comment by aaronyan** [comment]
Woo! Congrats on merging the new analysis @razvanpapadopol! 🎉 While looking around the different experiments, I think we can make a few quick adjustments

> {Variant} wins – There is high certainty that the variant is statistically and practically significant.
> Not enough data to make a recommendation at this time – The current results has high uncertainty, and collecting more data may improve certainty.

- I think we can adjust to "{Variant} winning" to communicate this is still collecting data. "Wins" feels too conclusive imo.
- "Not enough data to make a recommendation at this time" takes up a lot of space in the top-right recommendation. Let's try shortening to something else like "Not enough data" when showing at the top right.

<img width="1272" alt="Screen Shot 2022-05-05 at 5 44 26 PM" src="https://user-images.githubusercontent.com/4505888/167048913-6ca4b1ff-d44f-45af-8b11-6073695ec21b.png">

**Comment by aaronyan** [comment]
While testing out https://github.com/Automattic/abacus/pull/675, I had a few design ideas!

- Adjust "Relative change (lift)" to just "Lift"?
- Add "(Bottom)" and "(Top)" to credible interval diagrams header but in lighter grey?
- Replace "Absolute change" with "Impact (per month)" (https://github.com/Automattic/abacus/issues/710)
- Adjust simplified square diagram to a simple checkmark

Here's a mock-up of these changes! What do y'all think about?

<img width="961" alt="Group 58" src="https://user-images.githubusercontent.com/4505888/170150500-6bab6af7-f6ef-4396-b7de-3d14197636fa.png">

**Comment by aaronyan** [comment]
What do y'all think about scrapping the simplified square diagrams?

**Comment by jessie-ross** [comment]
Yeah I'd be for de-prioritising it at this point, but maybe bringing it back later.

**Comment by aaronyan** [comment]
> Add simplified square diagrams to metric overview header

What do y'all think about adding color to the credible interval diagram (for greater is better metrics)?

- `> min diff` -> green
- `< min diff` -> blue
-  `between min diff` -> yellow

Color would be used to help with the metric interpretation instead of using color to signal deployment action. Here's a mockup!

<img width="1680" alt="Screen Shot 2022-08-22 at 2 15 07 PM" src="https://user-images.githubusercontent.com/4505888/186020501-6d55891b-29be-4979-b5c1-a88d77a237a6.png">

**Comment by aaronyan** [comment]
Closing this for now!
