### ISSUE TITLE
Create an individual Metric page and routes

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/abacus#769]
Follow up for https://github.com/Automattic/abacus/issues/768, 
As mentioned in pbmo2S-1Am-p2#comment-254, we consider adding individual routes for each metric.

Format: `metrics/{metricId}` or `metrics/{metricId-metric-name}` as the experiment routes. Even if the latter may change once we archive metrics, it's probably doable to still do the matching.
**LE:** the matching works after updating the metric name (archiving) as it's based on the `metricId`, same as for the individual experiment.

- [x] add the new Metric page and support for the new routes #796
- [x] links from Experiment Overview & Results #829
- [x] links from Experiment Wizard #822
- [x] [shortcode link](https://github.com/Automattic/tampermonkey-highlighter) for metrics: `{metricId}-explat-metric` https://github.com/Automattic/tampermonkey-highlighter/pull/165

**Comment by razvanpapadopol** [comment]
This issue is now completed will all the items merged & released. The only immediate follow-up is the [PR adding a metric details modal](https://github.com/Automattic/abacus/pull/826) to improve the UX in the experiment wizard.
